message: Hello world!
# Be aware, this is generally unsafe unless you tryst your reverse-proxy
spring:
  application:
    name: helloworld
server:
  forward-headers-strategy: FRAMEWORK
info:
  version: "@project.version@"
  name: helloworld
logging:
  level:
    root: warn
    com.truemark.demo.helloworld: trace
