name: 'dev'

on: workflow_dispatch

jobs:
  call-common-workflow:
    uses: ./.github/workflows/common.yml
    with:
      TF_WORKSPACE: dev
      AWS_ACCOUNT_ID: "700430584483"
      AWS_REGION: us-west-2
    secrets:
      CONFIG_ACTIONS: ${{ secrets.CONFIG_ACTIONS }}
      APP_ID: ${{ secrets.APP_ID }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
