name: 'qa'


#  push:
#    branches: [ "truemark/github-actions", "truemark/github-actions-integration" ]
#  pull_request:
#    branches: [ "truemark/github-actions" ]
on: workflow_dispatch

jobs:
  call-common-workflow:
    uses: ./.github/workflows/common.yml
    with:
      TF_WORKSPACE: qa
      AWS_ACCOUNT_ID: "700430584483"
      AWS_REGION: us-west-2
    secrets:
      CONFIG_ACTIONS: ${{ secrets.CONFIG_ACTIONS }}
      APP_ID: ${{ secrets.APP_ID }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
